name: dgpc_cco
description: Sovereign Mission Control Console for DGPC
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.7.0
  firebase_storage: ^11.2.0
  google_maps_flutter: ^2.5.0
  provider: ^6.0.5
  intl: ^0.18.1
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
